server:
  port: 8083

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mariadb://mariadb:3306/lab-orders?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect

  rabbitmq:
    host: rabbitmq-service
    port: 5672
    username: user
    password: password

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

app:
  rabbit:
    queue-name: order-create-queue
    exchange-name: order-exchange
    routing-key: order-routing-key

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /index.html
