server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:mariadb://mariadb:3306/lab-products?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect

  cloud:
    discovery:
      enabled: true

  rabbitmq:
    host: rabbitmq-service
    port: 5672
    username: user
    password: password

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /index.html

app:
  rabbit:
    queue-name: order-create-queue
